[package]
name = "tuo-spec"
description = "Colocated executable specification infrastructure for tuonelang."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
tuo-source.workspace = true
tuo-diagnostics.workspace = true
tuo-resolve.workspace = true
tuo-mir.workspace = true
tuo-mir-interp.workspace = true
