[package]
name = "tuo-syntax"
description = "Lossless concrete syntax tree infrastructure for tuonelang."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
tuo-source.workspace = true
tuo-diagnostics.workspace = true
tuo-lexer.workspace = true
