[package]
name = "tuo-mir-interp"
description = "Reference MIR interpreter for tuonelang."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
tuo-source.workspace = true
tuo-diagnostics.workspace = true
tuo-resolve.workspace = true
tuo-types.workspace = true
tuo-mir.workspace = true

[dev-dependencies]
tuo-ast.workspace = true
tuo-parser.workspace = true
tuo-resolve.workspace = true
tuo-types.workspace = true
tuo-ownership.workspace = true
tuo-hir.workspace = true
