[package]
name = "tuo-mir"
description = "Mid-level IR (MIR): the single executable semantic representation of tuonelang."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
tuo-source.workspace = true
tuo-diagnostics.workspace = true
tuo-hir.workspace = true
tuo-resolve.workspace = true
tuo-types.workspace = true
tuo-ownership.workspace = true

[dev-dependencies]
tuo-ast.workspace = true
tuo-parser.workspace = true
