[package]
name = "tuo-resolve"
description = "Name and path resolution for tuonelang."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
tuo-source.workspace = true
tuo-diagnostics.workspace = true
tuo-ast.workspace = true

[dev-dependencies]
tuo-lexer.workspace = true
tuo-syntax.workspace = true
tuo-parser.workspace = true
