[package]
name = "tuo-lexer"
description = "Tokenizer for tuonelang source text."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
tuo-source.workspace = true
tuo-diagnostics.workspace = true
logos.workspace = true
unicode-normalization.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "throughput"
harness = false
